HotelApp.Web/Localization/ViewComponents/CultureSwitcherViewComponent.cs
namespace HotelApp.Web.Localization.ViewComponents;

using Models;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using System.Linq;

public class CultureSwitcherViewComponent : ViewComponent
{
    private readonly IOptions<RequestLocalizationOptions> _localizationOptions;

    public CultureSwitcherViewComponent(IOptions<RequestLocalizationOptions> localizationOptions) =>
        _localizationOptions = localizationOptions;

    public IViewComponentResult Invoke()
    {
        var cultureFeature = HttpContext.Features.Get<IRequestCultureFeature>()!;
        var model = new CultureSwitcherModel
        {
            SupportedCultures = _localizationOptions.Value.SupportedUICultures!.ToList(),
            CurrentUiCulture = cultureFeature.RequestCulture.UICulture
        };

        HttpContext.Response.Cookies.Append(
            CookieRequestCultureProvider.DefaultCookieName,
            CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(cultureFeature.RequestCulture.Culture)),
            new CookieOptions { Expires = DateTimeOffset.UtcNow.AddYears(1), Secure = true }
        );

        return View("Default", model);
    }
}

HotelApp.Web/Pages/BookRoom.cshtml.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Globalization;
using HotelAppLibrary.Data;
using HotelAppLibrary.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace HotelApp.Web.Pages
{
    public class BookRoomModel : PageModel
    {
        private readonly IDatabaseData _db;

        [BindProperty(SupportsGet = true)]
        public int RoomTypeId { get; set; }

        [DataType(DataType.Date)]
        [BindProperty(SupportsGet = true)]
        public DateTime CheckInDate { get; set; }

        [DataType(DataType.Date)]
        [BindProperty(SupportsGet = true)]
        public DateTime CheckOutDate { get; set; }

        [DisplayName("First name")]
        [BindProperty]
        public string? FirstName { get; set; }

        [DisplayName("Last name")]
        [BindProperty]
        public string? LastName { get; set; }

        public RoomTypeModel? RoomType { get; set; }

        public BookRoomModel(IDatabaseData db)
        {
            _db = db;
        }

        public void OnGet()
        {
            if (RoomTypeId > 0)
            {
                RoomType = _db.GetRoomTypeById(RoomTypeId);
            }
        }

        public IActionResult OnPost()
        {
            if (RoomTypeId > 0 && FirstName != null && LastName != null)
            {
                _db.BookGuest(FirstName, LastName, CheckInDate, CheckOutDate, RoomTypeId);
            }

            return RedirectToPage("/Index");
        }
    }
}

HotelApp.Web/Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace HotelApp.Web.Pages;

[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
[IgnoreAntiforgeryToken]
public class ErrorModel : PageModel
{
    private readonly ILogger<ErrorModel> _logger;

    public ErrorModel(ILogger<ErrorModel> logger)
    {
        _logger = logger;
    }

    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

    public void OnGet()
    {
        RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
    }
}

HotelApp.Web/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace HotelApp.Web.Pages;

public class IndexModel : PageModel
{
    private readonly ILogger<IndexModel> _logger;

    public IndexModel(ILogger<IndexModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
    }
}

HotelApp.Web/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace HotelApp.Web.Pages;

public class PrivacyModel : PageModel
{
    private readonly ILogger<PrivacyModel> _logger;

    public PrivacyModel(ILogger<PrivacyModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
    }
}

HotelApp.Web/Pages/RoomSearch.cshtml.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Globalization;
using HotelAppLibrary.Data;
using HotelAppLibrary.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace HotelApp.Web.Pages
{
    public class RoomSearchModel : PageModel
    {
        private readonly IDatabaseData _db;

        [DisplayName("Check-in date")]
        [BindProperty(SupportsGet = true)]
        [DataType(DataType.Date)]
        public DateTime CheckInDate { get; set; } = DateTime.Now;

        [DisplayName("Check-out date")]
        [BindProperty(SupportsGet = true)]
        [DataType(DataType.Date)]
        public DateTime CheckOutDate { get; set; } = DateTime.Now.AddDays(1);

        [BindProperty(SupportsGet = true)]
        public bool IsSearchEnabled { get; set; } = false;

        public List<RoomTypeModel>? AvailableRoomTypes { get; set; }

        public RoomSearchModel(IDatabaseData db)
        {
            _db = db;
        }

        public void OnGet()
        {
            if (IsSearchEnabled)
            {
                AvailableRoomTypes = _db.GetAvailableRoomTypes(CheckInDate, CheckOutDate);
            }
        }

        public IActionResult OnPost()
        {
            return RedirectToPage(
                new
                {
                    IsSearchEnabled = true,
                    CheckInDate = CheckInDate.ToString("yyyy-MM-dd"),
                    CheckOutDate = CheckOutDate.ToString("yyyy-MM-dd")
                }
            );
        }
    }
}

HotelApp.Web/Pages/BookRoom.cshtml
@page
@using Microsoft.AspNetCore.Localization
@model HotelApp.Web.Pages.BookRoomModel
@{
    ViewData["Title"] = "Book A Room";
    var requestCultureFeature = HttpContext.Features.Get<IRequestCultureFeature>()!;
    var requestCulture = requestCultureFeature.RequestCulture;
}

<h1 class="mb-4">Book A Room</h1>

@if (@Model.RoomType == null)
{
    <p>Error: Room with ID @Model.RoomTypeId was not found.</p>
}
else
{
    <section class="mb-4">
        <h2 class="h3">@Model.RoomType.Title</h2>
        <p>@Model.RoomType.Description</p>
    </section>

    <section class="mb-4">
        <h2 class="h3">Dates</h2>
        <p>
            @Model.CheckInDate.ToString("d", requestCulture.UICulture) -
            @Model.CheckOutDate.ToString("d", requestCulture.UICulture)
        </p>
    </section>

    <form method="post" class="mb-5">
        <div class="row">
            <div class="mb-3 col">
                <label asp-for="@Model.FirstName"></label>
                <input asp-for="@Model.FirstName" class="form-control"/>
            </div>
            <div class="mb-3 col">
                <label asp-for="@Model.LastName"></label>
                <input asp-for="@Model.LastName" class="form-control"/>
            </div>
        </div>
        <button type="submit" class="btn btn-primary">Book</button>
    </form>
}

HotelApp.Web/Pages/Index.cshtml
@page
@using Microsoft.AspNetCore.Localization
@model IndexModel
@{
    ViewData["Title"] = "Home page";
    var requestCultureFeature = HttpContext.Features.Get<IRequestCultureFeature>()!;
    var requestCulture = requestCultureFeature.RequestCulture;
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>

    <table class="table culture-table">
        <tr>
            <td style="width: 50%;">Culture</td>
            <td>@requestCulture.Culture.DisplayName {@requestCulture.Culture.Name}</td>
        </tr>
        <tr>
            <td>UI Culture</td>
            <td>@requestCulture.UICulture.Name</td>
        </tr>
        <tr>
            <td>UICulture Parent</td>
            <td>@requestCulture.UICulture.Parent</td>
        </tr>
        <tr>
            <td>Date</td>
            <td>@DateTime.Now.ToLongDateString()</td>
        </tr>
        <tr>
            <td>Currency</td>
            <td>
                @(12345.00.ToString("c"))
            </td>
        </tr>
        <tr>
            <td>Number</td>
            <td>
                @(123.45m.ToString("F2"))
            </td>
        </tr>
    </table>
</div>

HotelApp.Web/Pages/RoomSearch.cshtml
@page
@using System.Globalization
@using Microsoft.AspNetCore.Mvc.TagHelpers
@model HotelApp.Web.Pages.RoomSearchModel
@{
    ViewData["Title"] = "Room Search";
}

<h1 class="mb-4">Room Search</h1>

<form method="post" class="mb-5">
    <div class="row">
        <div class="mb-3 col">
            <label asp-for="@Model.CheckInDate"></label>
            <input asp-for="@Model.CheckInDate" class="form-control"/>
        </div>
        <div class="mb-3 col">
            <label asp-for="@Model.CheckOutDate"></label>
            <input asp-for="@Model.CheckOutDate" class="form-control"/>
        </div>
    </div>
    <button type="submit" class="btn btn-primary">Search</button>
</form>

@if (Model.AvailableRoomTypes != null)
{
    <h2 class="mb-4">Results</h2>

    @if (Model.AvailableRoomTypes.Count == 0)
    {
        <p>No rooms available for selected dates.</p>
    }
    else
    {
        <table class="table align-middle">
            <thead>
            <tr>
                <th scope="col">Room Type</th>
                <th scope="col">Price</th>
                <th scope="col"></th>
            </tr>
            </thead>
            <tbody>
            @foreach (var roomType in Model.AvailableRoomTypes)
            {
                <tr>
                    <td>
                        <h3 class="h5 mb-0">@roomType.Title</h3>
                        <p class="text-muted mb-0">@roomType.Description</p>
                    </td>
                    <td>@(@roomType.Price.ToString("C"))</td>
                    <td>
                        <a
                            asp-page="/BookRoom"
                            asp-route-checkindate="@Model.CheckInDate.ToString("O")"
                            asp-route-checkoutdate="@Model.CheckOutDate.ToString("O")"
                            asp-route-roomtypeid="@roomType.Id"
                            class="btn btn-link">
                            Book room
                        </a>
                    </td>
                </tr>
            }
            </tbody>
        </table>
    }
}

HotelApp.Web/Pages/Shared/Components/CultureSwitcher/Default.cshtml
@using Microsoft.AspNetCore.Mvc.TagHelpers
@model HotelApp.Web.Localization.Models.CultureSwitcherModel

<div>
    @if (Model.SupportedCultures?.Count > 0)
    {
        <form id="culture-switcher">
            <select name="culture" id="culture-options" class="form-select">
                <option></option>
                @foreach (var culture in Model.SupportedCultures)
                {
                    <option value="@culture.Name" selected="@(Model.CurrentUiCulture?.Name == culture.Name)">@culture.DisplayName</option>
                }
            </select>
        </form>
    }
    else
    {
        <p>Empty</p>
    }
</div>

<script>
    document
        .getElementById("culture-options")
        .addEventListener("change", () => document.getElementById("culture-switcher").submit());
</script>

HotelApp.Web/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - HotelApp.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/HotelApp.Web.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-page="/Index">HotelApp.Web</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-page="/RoomSearch">Room Search</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                    </li>
                </ul>
            </div>
            @* https://github.com/dotnet/razor/issues/8281 *@
            @await Component.InvokeAsync("CultureSwitcher")
        </div>
    </nav>

</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2023 - HotelApp.Web - <a asp-area="" asp-page="/Privacy">Privacy</a>
    </div>
</footer>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>

@await RenderSectionAsync("Scripts", false)
</body>
</html>